"""RegistryAPIClient — httpx-based client for registry-api endpoints (Story 3.3 AC-1, AC-2).

Wraps POST /v1/tasks. The client holds a pre-built ``httpx.AsyncClient``
that is constructed ONCE at lifespan startup (Story 3.1 H4 cache-once
pattern) and reused across all handler invocations. Never construct a
new ``AsyncClient`` per-request.

Architecture boundary
---------------------
``CreateTaskResponseLocal`` is redefined here rather than imported from
``registry_api.routes.tasks``.  This keeps the transport boundary clean:
the cross-service contract is HTTP/JSON (architecture.md:231), not shared
Python objects.  See AC-2 doc-comment for details.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

import httpx
from pydantic import BaseModel, ConfigDict


class CreateTaskResponseLocal(BaseModel):
    """Local mirror of registry-api's CreateTaskResponse (Story 2.9).

    Redefined here to avoid a services→services import (architecture.md:231 keeps
    the cross-service contract as HTTP/JSON, not shared Python objects).
    Source-of-truth for field layout: services/registry-api/src/registry_api/routes/tasks.py
    class CreateTaskResponse. Review-time validation: field names must match registry-api's
    serialised JSON keys. TODO(architecture): migrate shared models to packages/events/ if
    the cross-service model count grows beyond 3.
    """

    model_config = ConfigDict(frozen=True)

    task_id: str
    event_id: str
    created_at: datetime
    # Derived from X-Idempotency-Status response header (AC-7 / AC-10).
    # "applied" = first successful submission; "replayed" = Telegram retry
    # deduplicated by registry-api (FR28). Defaults to "applied" when the
    # header is absent (e.g., older registry-api versions).
    idempotency_status: Literal["applied", "replayed"] = "applied"


class RegistryAPIClient:
    """httpx-based client for registry-api endpoints used by Telegram handlers.

    Wraps POST /v1/tasks. Constructor takes a pre-built AsyncClient (lifespan-owned,
    reusable across requests — Story 3.1 H4 cache-once pattern).
    """

    def __init__(self, *, base_url: str, http_client: httpx.AsyncClient) -> None:
        """Initialise with an already-built long-lived AsyncClient.

        Args:
            base_url:    Base URL for registry-api (e.g. "http://registry-api:8080").
                         Stored for reference; actual routing uses the ``base_url``
                         baked into ``http_client`` at construction time.
            http_client: Lifespan-owned ``httpx.AsyncClient``.  NEVER pass a
                         per-request client — that would leave dangling connections
                         and defeat the TLS session-reuse benefit.
        """
        self._base_url = base_url
        self._http_client = http_client

    @property
    def http_client(self) -> httpx.AsyncClient:
        """Expose the underlying AsyncClient (for identity-check tests)."""
        return self._http_client

    async def create_task(
        self,
        *,
        description: str,
        idempotency_key: str,
        operator_actor_id: str,
        request_id: str | None = None,
    ) -> CreateTaskResponseLocal:
        """POST /v1/tasks and return a typed local response model.

        Args:
            description:       Task title / free-text description (maps to
                               ``CreateTaskRequest.title`` in registry-api).
            idempotency_key:   Deterministic key derived from ``(chat_id, message_id)``
                               so Telegram retries map to the same task (FR28).
            operator_actor_id: Telegram user id of the operator (Phase 1 actor hint;
                               real auth lands in Story 6.1+).
            request_id:        UUIDv7 request correlation id (architecture.md:313).
                               Forwarded as ``X-Request-ID``; generated by the caller.

        Returns:
            :class:`CreateTaskResponseLocal` on HTTP 201.

        Raises:
            httpx.HTTPStatusError: On non-2xx responses with the raw httpx
                ``Response`` attached so callers can inspect status and RFC 7807
                body (architecture.md:228).
            httpx.HTTPError:       On network / timeout errors.
        """
        headers: dict[str, str] = {
            "Idempotency-Key": idempotency_key,
            # Phase 1: pass the operator Telegram id as a hint header.
            # Story 6.1 replaces this with a proper auth token.
            "X-Actor-Id": operator_actor_id,
        }
        if request_id is not None:
            headers["X-Request-ID"] = request_id

        response = await self._http_client.post(
            "/v1/tasks",
            json={"title": description},
            headers=headers,
        )
        response.raise_for_status()

        data = response.json()
        idempotency_status: Literal["applied", "replayed"] = (
            "replayed" if response.headers.get("X-Idempotency-Status") == "replayed" else "applied"
        )
        return CreateTaskResponseLocal(
            task_id=data["task_id"],
            event_id=data["event_id"],
            created_at=data["created_at"],
            idempotency_status=idempotency_status,
        )


__all__ = ["CreateTaskResponseLocal", "RegistryAPIClient"]
