"""RegistryAPIClient — httpx-based client for registry-api endpoints (Story 3.3 AC-1, AC-2).

Wraps POST /v1/tasks and POST /v1/tasks/{id}/decisions. The client holds a
pre-built ``httpx.AsyncClient`` that is constructed ONCE at lifespan startup
(Story 3.1 H4 cache-once pattern) and reused across all handler invocations.
Never construct a new ``AsyncClient`` per-request.

Architecture boundary
---------------------
``CreateTaskResponseLocal`` and ``DecisionResponseLocal`` are redefined here
rather than imported from ``registry_api.routes.tasks``.  This keeps the
transport boundary clean: the cross-service contract is HTTP/JSON
(architecture.md:231), not shared Python objects.  See AC-2 doc-comment for
details.
"""

from __future__ import annotations

import json as _json
from datetime import datetime
from typing import Literal

import httpx
from pydantic import BaseModel, ConfigDict, ValidationError


class CreateTaskResponseLocal(BaseModel):
    """Local mirror of registry-api's CreateTaskResponse (Story 2.9).

    Redefined here to avoid a services→services import (architecture.md:231 keeps
    the cross-service contract as HTTP/JSON, not shared Python objects).
    Source-of-truth for field layout: services/registry-api/src/registry_api/routes/tasks.py
    class CreateTaskResponse. Review-time validation: field names must match registry-api's
    serialised JSON keys. TODO(architecture): migrate shared models to packages/events/ if
    the cross-service model count grows beyond 3.
    """

    model_config = ConfigDict(frozen=True)

    task_id: str
    event_id: str
    created_at: datetime
    # Derived from X-Idempotency-Status response header (AC-7 / AC-10).
    # "applied" = first successful submission; "replayed" = Telegram retry
    # deduplicated by registry-api (FR28). Defaults to "applied" when the
    # header is absent (e.g., older registry-api versions).
    idempotency_status: Literal["applied", "replayed"] = "applied"


class RegistryAPIClient:
    """httpx-based client for registry-api endpoints used by Telegram handlers.

    Wraps POST /v1/tasks. Constructor takes a pre-built AsyncClient (lifespan-owned,
    reusable across requests — Story 3.1 H4 cache-once pattern).
    """

    def __init__(self, *, http_client: httpx.AsyncClient) -> None:
        """Initialise with an already-built long-lived AsyncClient.

        Args:
            http_client: Lifespan-owned ``httpx.AsyncClient``.  NEVER pass a
                         per-request client — that would leave dangling connections
                         and defeat the TLS session-reuse benefit.  The client's
                         ``base_url`` must already be set to the registry-api base
                         URL (e.g. ``http://registry-api:8080``) at construction.
        """
        self._http_client = http_client

    @property
    def http_client(self) -> httpx.AsyncClient:
        """Expose the underlying AsyncClient (for identity-check tests)."""
        return self._http_client

    async def create_task(
        self,
        *,
        description: str,
        idempotency_key: str,
        operator_actor_id: str,
        request_id: str | None = None,
    ) -> CreateTaskResponseLocal:
        """POST /v1/tasks and return a typed local response model.

        Args:
            description:       Task title / free-text description (maps to
                               ``CreateTaskRequest.title`` in registry-api).
            idempotency_key:   Deterministic key derived from ``(chat_id, message_id)``
                               so Telegram retries map to the same task (FR28).
            operator_actor_id: Telegram user id of the operator (Phase 1 actor hint;
                               real auth lands in Story 6.1+).
            request_id:        UUIDv7 request correlation id (architecture.md:313).
                               Forwarded as ``X-Request-ID``; generated by the caller.

        Returns:
            :class:`CreateTaskResponseLocal` on HTTP 201.

        Raises:
            httpx.HTTPStatusError: On non-2xx responses with the raw httpx
                ``Response`` attached so callers can inspect status and RFC 7807
                body (architecture.md:228).
            httpx.HTTPError:       On network / timeout errors, including when
                registry-api returns a malformed body on a 2xx response.
        """
        headers: dict[str, str] = {
            "Idempotency-Key": idempotency_key,
            # Phase 1: pass the operator Telegram id as a hint header.
            # Story 6.1 replaces this with a proper auth token.
            "X-Actor-Id": operator_actor_id,
        }
        if request_id is not None:
            headers["X-Request-ID"] = request_id

        response = await self._http_client.post(
            "/v1/tasks",
            json={"title": description},
            headers=headers,
        )
        response.raise_for_status()

        # H2: wrap body parsing so shape failures route into handle_task's
        # existing httpx.HTTPError catch rather than escaping as untyped exceptions.
        try:
            data = response.json()
            idempotency_status: Literal["applied", "replayed"] = (
                "replayed"
                if response.headers.get("X-Idempotency-Status") == "replayed"
                else "applied"
            )
            return CreateTaskResponseLocal(
                task_id=data["task_id"],
                event_id=data["event_id"],
                created_at=data["created_at"],
                idempotency_status=idempotency_status,
            )
        except (_json.JSONDecodeError, KeyError, ValidationError) as exc:
            raise httpx.HTTPError(f"registry-api returned malformed body: {exc}") from exc

    async def submit_decision(
        self,
        *,
        task_id: str,
        action: Literal["approve", "reject", "stop", "retry"],
        idempotency_key: str,
        operator_actor_id: str,
        request_id: str | None = None,
        hint: str | None = None,
    ) -> DecisionResponseLocal:
        """POST /v1/tasks/{task_id}/decisions and return a typed local response model.

        Args:
            task_id:           The "t-<uuidv7>" task identifier.
            action:            Decision action: "approve", "reject", "stop", or "retry".
            idempotency_key:   Deterministic key derived from ``(chat_id, message_id)``
                               so Telegram retries map to the same decision (FR28).
            operator_actor_id: Telegram user id of the operator (Phase 1 actor hint).
            request_id:        UUIDv7 request correlation id (architecture.md:313).
                               Forwarded as ``X-Request-ID``; generated by the caller.
            hint:              Optional free-text hint for the orchestrator's next planning
                               pass (FR7). Omitted from the POST body when None.

        Returns:
            :class:`DecisionResponseLocal` on HTTP 2xx.

        Raises:
            httpx.HTTPStatusError: On non-2xx responses with the raw httpx
                ``Response`` attached so callers can inspect status and RFC 7807
                body (architecture.md:228).
            httpx.HTTPError:       On network / timeout errors, including when
                registry-api returns a malformed body on a 2xx response (H2).

        Note:
            POST /v1/tasks/{id}/decisions does NOT exist server-side yet.
            Story 6.4 owns the implementation. Until then a live call returns
            404. Tests mock the transport layer so they are runnable today.
            TODO(story-6.4): verify DecisionResponseLocal field names match
            Story 6.4's serialised JSON keys when that endpoint lands.
        """
        headers: dict[str, str] = {
            "Idempotency-Key": idempotency_key,
            "X-Actor-Id": operator_actor_id,
        }
        if request_id is not None:
            headers["X-Request-ID"] = request_id

        # Omit hint key entirely when None (forward-compat with Story 3.18).
        body: dict[str, str] = {"action": action}
        if hint is not None:
            body["hint"] = hint

        response = await self._http_client.post(
            f"/v1/tasks/{task_id}/decisions",
            json=body,
            headers=headers,
        )
        response.raise_for_status()

        # H2: wrap body parsing so shape failures route into handle_approve's
        # existing httpx.HTTPError catch rather than escaping as untyped exceptions.
        try:
            data = response.json()
            idempotency_status: Literal["applied", "replayed"] = (
                "replayed"
                if response.headers.get("X-Idempotency-Status") == "replayed"
                else "applied"
            )
            return DecisionResponseLocal(
                task_id=data["task_id"],
                decision_id=data["decision_id"],
                action=data["action"],
                decided_at=data["decided_at"],
                idempotency_status=idempotency_status,
            )
        except (_json.JSONDecodeError, KeyError, ValidationError) as exc:
            raise httpx.HTTPError(f"registry-api returned malformed body: {exc}") from exc


class DecisionResponseLocal(BaseModel):
    """Local mirror of registry-api's eventual DecisionResponse (Story 6.4 owns server-side).

    Forward-compatible shape pinned by 3.4's mocked tests; review-time validation
    must align with 6.4's POST /v1/tasks/{id}/decisions response when that endpoint lands.
    Source-of-truth: services/registry-api/src/registry_api/routes/tasks.py (Story 6.4).
    Architecture note: local redefinition keeps cross-service contract as HTTP/JSON
    (architecture.md:231) — same decision as CreateTaskResponseLocal (Story 3.3 AC-2).

    TODO(story-6.4): verify field names match Story 6.4's serialised JSON keys.
    """

    model_config = ConfigDict(frozen=True)

    task_id: str
    decision_id: str  # "d-<uuidv7>" per FR7 audit trail
    action: Literal["approve", "reject", "stop", "retry"]
    decided_at: datetime
    idempotency_status: Literal["applied", "replayed"] = "applied"


__all__ = ["CreateTaskResponseLocal", "DecisionResponseLocal", "RegistryAPIClient"]
